import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';

import '../styles/globals.css';
import Providers from './providers';
const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br" className="bg-black">
      <body className={`${plusJakartaSans.className} bg-black`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
