interface Countries {
  [key: string]: string;
}

export const COUNTRIES: Countries = {
  DZ: 'Argélia',
  AR: 'Argentina',
  AU: 'Austrália',
  AT: 'Áustria',
  AZ: 'Azerbaijão',
  BH: 'Bahrein',
  BD: 'Bangladesh',
  BY: 'Bielorrússia',
  BE: 'Bélgica',
  BO: 'Bolívia',
  BA: 'Bósnia e Herzegovina',
  BR: 'Brasil',
  BG: 'Bulgária',
  KH: 'Camboja',
  CA: 'Canadá',
  CL: 'Chile',
  CO: 'Colômbia',
  CR: 'Costa Rica',
  HR: 'Croácia',
  CY: 'Chipre',
  CZ: 'República Tcheca',
  DK: 'Dinamarca',
  DO: 'República Dominicana',
  EC: 'Equador',
  EG: 'Egito',
  SV: 'El Salvador',
  EE: 'Estônia',
  FI: 'Finlândia',
  FR: 'França',
  GE: 'Geórgia',
  DE: 'Alemanha',
  GH: 'Gana',
  GR: 'Grécia',
  GT: 'Guatemala',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungria',
  IS: 'Islândia',
  IN: 'Índia',
  ID: 'Indonésia',
  IQ: 'Iraque',
  IE: 'Irlanda',
  IL: 'Israel',
  IT: 'Itália',
  JM: 'Jamaica',
  JP: 'Japão',
  JO: 'Jordânia',
  KZ: 'Cazaquistão',
  KE: 'Quênia',
  KW: 'Kuwait',
  LA: 'Laos',
  LV: 'Letônia',
  LB: 'Líbano',
  LY: 'Líbia',
  LI: 'Liechtenstein',
  LT: 'Lituânia',
  LU: 'Luxemburgo',
  MY: 'Malásia',
  MT: 'Malta',
  MX: 'México',
  ME: 'Montenegro',
  MA: 'Marrocos',
  NP: 'Nepal',
  NL: 'Países Baixos',
  NZ: 'Nova Zelândia',
  NI: 'Nicarágua',
  NG: 'Nigéria',
  MK: 'Macedônia do Norte',
  NO: 'Noruega',
  OM: 'Omã',
  PK: 'Paquistão',
  PA: 'Panamá',
  PG: 'Papua-Nova Guiné',
  PY: 'Paraguai',
  PE: 'Peru',
  PH: 'Filipinas',
  PL: 'Polônia',
  PT: 'Portugal',
  PR: 'Porto Rico',
  QA: 'Catar',
  RO: 'Romênia',
  RU: 'Rússia',
  SA: 'Arábia Saudita',
  SN: 'Senegal',
  RS: 'Sérvia',
  SG: 'Singapura',
  SK: 'Eslováquia',
  SI: 'Eslovênia',
  ZA: 'África do Sul',
  KR: 'Coreia do Sul',
  ES: 'Espanha',
  LK: 'Sri Lanka',
  SE: 'Suécia',
  CH: 'Suíça',
  TW: 'Taiwan',
  TZ: 'Tanzânia',
  TH: 'Tailândia',
  TN: 'Tunísia',
  TR: 'Turquia',
  UG: 'Uganda',
  UA: 'Ucrânia',
  AE: 'Emirados Árabes Unidos',
  GB: 'Reino Unido',
  US: 'Estados Unidos',
  UY: 'Uruguai',
  VE: 'Venezuela',
  VN: 'Vietnã',
  YE: 'Iêmen',
  ZW: 'Zimbábue'
};
