export const PIPED_VALUES = {
  VIDEO_TYPES: {
    DASH_XML_DATA_URI: 'data:application/dash+xml;charset=utf-8;base64,',
    MP4_VIDEO_TYPE: 'video/mp4'
  },

  ENDPOINTS: {
    INSTANCES: 'https://piped-instances.kavin.rocks/'
  },

  DEFAULT_INSTANCE_LIST: [
    {
      name: 'lunar.icu',
      api_url: 'https://piped-api.lunar.icus'
    },
    {
      name: 'kavin.rocks (Official)',
      api_url: 'https://pipedapi.kavin.rocks'
    },
    {
      name: 'kavin.rocks libre (Official)',
      api_url: 'https://pipedapi-libre.kavin.rocks'
    },
    {
      name: 'leptons.xyz',
      api_url: 'https://pipedapi.leptons.xyz'
    },
    {
      name: 'r4fo.com',
      api_url: 'https://pipedapi.r4fo.com'
    },
    {
      name: 'projectsegfau.lt',
      api_url: 'https://api.piped.projectsegfau.lt'
    },
    {
      name: 'projectsegfau.lt in',
      api_url: 'https://pipedapi.in.projectsegfau.lt'
    },
    {
      name: 'projectsegfau.lt us',
      api_url: 'https://pipedapi.us.projectsegfau.lt'
    },
    {
      name: 'privacydev.net',
      api_url: 'https://api.piped.privacydev.net'
    },
    {
      name: 'smnz.de',
      api_url: 'https://pipedapi.smnz.de'
    },
    {
      name: 'adminforge.de',
      api_url: 'https://pipedapi.adminforge.de'
    },
    {
      name: 'astartes.nl',
      api_url: 'https://pipedapi.astartes.nl'
    },
    {
      name: 'drgns.space',
      api_url: 'https://pipedapi.drgns.space'
    },
    {
      name: 'ggtyler.dev',
      api_url: 'https://piapi.ggtyler.dev'
    },
    {
      name: 'seitan-ayoub.lol',
      api_url: 'https://piped-backend.seitan-ayoub.lol'
    },
    {
      name: 'ngn.tf',
      api_url: 'https://pipedapi.ngn.tf'
    }
  ],

  DEFAULT_INSTANCE: {
    name: 'kavin.rocks libre (Official)',
    api_url: 'https://pipedapi-libre.kavin.rocks'
  },

  DEFAULT_REGION: 'BR',

  REGIONS: [
    'DZ',
    'AR',
    'AU',
    'AT',
    'AZ',
    'BH',
    'BD',
    'BY',
    'BE',
    'BO',
    'BA',
    'BR',
    'BG',
    'KH',
    'CA',
    'CL',
    'CO',
    'CR',
    'HR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'EC',
    'EG',
    'SV',
    'EE',
    'FI',
    'FR',
    'GE',
    'DE',
    'GH',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IN',
    'ID',
    'IQ',
    'IE',
    'IL',
    'IT',
    'JM',
    'JP',
    'JO',
    'KZ',
    'KE',
    'KW',
    'LA',
    'LV',
    'LB',
    'LY',
    'LI',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'ME',
    'MA',
    'NP',
    'NL',
    'NZ',
    'NI',
    'NG',
    'MK',
    'NO',
    'OM',
    'PK',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'PR',
    'QA',
    'RO',
    'RU',
    'SA',
    'SN',
    'RS',
    'SG',
    'SK',
    'SI',
    'ZA',
    'KR',
    'ES',
    'LK',
    'SE',
    'CH',
    'TW',
    'TZ',
    'TH',
    'TN',
    'TR',
    'UG',
    'UA',
    'AE',
    'GB',
    'US',
    'UY',
    'VE',
    'VN',
    'YE',
    'ZW'
  ],

  DEFAULT_INSTANCE_CONFIG: {
    imageProxyUrl: 'https://pipedproxy.kavin.rocks',
    countries: [
      'DZ',
      'AR',
      'AU',
      'AT',
      'AZ',
      'BH',
      'BD',
      'BY',
      'BE',
      'BO',
      'BA',
      'BR',
      'BG',
      'KH',
      'CA',
      'CL',
      'CO',
      'CR',
      'HR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'EC',
      'EG',
      'SV',
      'EE',
      'FI',
      'FR',
      'GE',
      'DE',
      'GH',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IN',
      'ID',
      'IQ',
      'IE',
      'IL',
      'IT',
      'JM',
      'JP',
      'JO',
      'KZ',
      'KE',
      'KW',
      'LA',
      'LV',
      'LB',
      'LY',
      'LI',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'ME',
      'MA',
      'NP',
      'NL',
      'NZ',
      'NI',
      'NG',
      'MK',
      'NO',
      'OM',
      'PK',
      'PA',
      'PG',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'PR',
      'QA',
      'RO',
      'RU',
      'SA',
      'SN',
      'RS',
      'SG',
      'SK',
      'SI',
      'ZA',
      'KR',
      'ES',
      'LK',
      'SE',
      'CH',
      'TW',
      'TZ',
      'TH',
      'TN',
      'TR',
      'UG',
      'UA',
      'AE',
      'GB',
      'US',
      'UY',
      'VE',
      'VN',
      'YE',
      'ZW'
    ],
    s3Enabled: true,
    registrationDisabled: false
  }
};
