export const PIPED_VALUES = {
  VIDEO_TYPES: {
    DASH_XML_DATA_URI: 'data:application/dash+xml;charset=utf-8;base64,',
    MP4_VIDEO_TYPE: 'video/mp4'
  },

  ENDPOINTS: {
    INSTANCES: 'https://piped-instances.kavin.rocks/'
  },

  DEFAULT_INSTANCE_LIST: [
    {
      name: 'kavin.rocks (Official)',
      api_url: 'https://pipedapi.kavin.rocks',
      locations: '🇺🇸, 🇮🇳, 🇳🇱, 🇨🇦, 🇬🇧, 🇫🇷',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: true,
      registered: 222942,
      last_checked: 1706786270,
      cache: true,
      s3_enabled: true,
      image_proxy_url: 'https://pipedproxy.kavin.rocks',
      registration_disabled: false,
      uptime_24h: 81.33659,
      uptime_7d: 91.12969,
      uptime_30d: 95.69189
    },
    {
      name: 'lunar.icu',
      api_url: 'https://piped-api.lunar.icus',
      locations: '🇩🇪',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: true,
      registered: 1694,
      last_checked: 1706786270,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://piped-proxy.lunar.icu',
      registration_disabled: false,
      uptime_24h: 82.95269,
      uptime_7d: 93.19609,
      uptime_30d: 95.79535
    },
    {
      name: 'r4fo.com',
      api_url: 'https://pipedapi.r4fo.com',
      locations: '🇩🇪',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: true,
      registered: 764,
      last_checked: 1706786270,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://pipedproxy.r4fo.com',
      registration_disabled: false,
      uptime_24h: 99.022,
      uptime_7d: 97.189644,
      uptime_30d: 97.60242
    },
    {
      name: 'kavin.rocks libre (Official)',
      api_url: 'https://pipedapi-libre.kavin.rocks',
      locations: '🇳🇱',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 222942,
      last_checked: 1706786269,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://pipedproxy-ams-2.kavin.rocks',
      registration_disabled: false,
      uptime_24h: 68.15235,
      uptime_7d: 43.676575,
      uptime_30d: 79.634254
    },
    {
      name: 'projectsegfau.lt',
      api_url: 'https://api.piped.projectsegfau.lt',
      locations: '🇫🇷',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 1042,
      last_checked: 1706786269,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://proxy.piped.projectsegfau.lt',
      registration_disabled: false,
      uptime_24h: 94.13203,
      uptime_7d: 92.83971,
      uptime_30d: 77.55819
    },
    {
      name: 'projectsegfau.lt in',
      api_url: 'https://pipedapi.in.projectsegfau.lt',
      locations: '🇮🇳',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 1725,
      last_checked: 1706786271,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://pipedproxy.in.projectsegfau.lt',
      registration_disabled: false,
      uptime_24h: 99.8366,
      uptime_7d: 95.20261,
      uptime_30d: 79.18222
    },
    {
      name: 'projectsegfau.lt us',
      api_url: 'https://pipedapi.us.projectsegfau.lt',
      locations: '🇺🇸',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 808,
      last_checked: 1706805126,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://proxy.piped.projectsegfau.lt',
      registration_disabled: false,
      uptime_24h: 8.927109,
      uptime_7d: 47.424366,
      uptime_30d: 77.43466
    },
    {
      name: 'privacydev.net',
      api_url: 'https://api.piped.privacydev.net',
      locations: '🇫🇷',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 1278,
      last_checked: 1706786270,
      cache: false,
      s3_enabled: false,
      image_proxy_url: 'https://proxy.piped.privacydev.net',
      registration_disabled: false,
      uptime_24h: 83.97384,
      uptime_7d: 81.24636,
      uptime_30d: 80.433365
    },
    {
      name: 'smnz.de',
      api_url: 'https://pipedapi.smnz.de',
      locations: '🇩🇪',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 1478,
      last_checked: 1706786270,
      cache: false,
      s3_enabled: false,
      image_proxy_url: 'https://pipedimageproxy.smnz.de',
      registration_disabled: true,
      uptime_24h: 99.10277,
      uptime_7d: 94.69459,
      uptime_30d: 98.27258
    },
    {
      name: 'adminforge.de',
      api_url: 'https://pipedapi.adminforge.de',
      locations: '🇩🇪',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 5814,
      last_checked: 1706786270,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://pipedimg.adminforge.de',
      registration_disabled: false,
      uptime_24h: 99.7553,
      uptime_7d: 98.38616,
      uptime_30d: 99.298515
    },
    {
      name: 'astartes.nl',
      api_url: 'https://pipedapi.astartes.nl',
      locations: '🇳🇱',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 0,
      last_checked: 1706786270,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://pipedproxy.astartes.nl',
      registration_disabled: true,
      uptime_24h: 98.20408,
      uptime_7d: 97.593864,
      uptime_30d: 96.09492
    },
    {
      name: 'drgns.space',
      api_url: 'https://pipedapi.drgns.space',
      locations: '🇺🇸',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 45,
      last_checked: 1706786270,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://pipedproxy.drgns.space',
      registration_disabled: false,
      uptime_24h: 97.79951,
      uptime_7d: 64.78824,
      uptime_30d: 49.74296
    },
    {
      name: 'ggtyler.dev',
      api_url: 'https://piapi.ggtyler.dev',
      locations: '🇺🇸',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 1472,
      last_checked: 1706786270,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://piproxy.ggtyler.dev',
      registration_disabled: false,
      uptime_24h: 98.85901,
      uptime_7d: 98.84884,
      uptime_30d: 98.70438
    },
    {
      name: 'seitan-ayoub.lol',
      api_url: 'https://piped-backend.seitan-ayoub.lol',
      locations: '🇩🇪',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 321,
      last_checked: 1706786271,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://piped-proxy.seitan-ayoub.lol',
      registration_disabled: false,
      uptime_24h: 99.755104,
      uptime_7d: 99.4762,
      uptime_30d: 91.57456
    },
    {
      name: 'ngn.tf',
      api_url: 'https://pipedapi.ngn.tf',
      locations: '🇹🇷',
      version: '2023-12-19-c746794',
      up_to_date: true,
      cdn: false,
      registered: 1,
      last_checked: 1706805126,
      cache: true,
      s3_enabled: false,
      image_proxy_url: 'https://pipedproxy.ngn.tf',
      registration_disabled: false,
      uptime_24h: 25.898691,
      uptime_7d: 85.24686,
      uptime_30d: 81.33306
    }
  ],

  DEFAULT_INSTANCE: {
    name: 'kavin.rocks libre (Official)',
    api_url: 'https://pipedapi-libre.kavin.rocks',
    locations: '🇳🇱',
    version: '2023-12-19-c746794',
    up_to_date: true,
    cdn: false,
    registered: 219427,
    last_checked: 1705044218,
    cache: true,
    s3_enabled: false,
    image_proxy_url: 'https://pipedproxy-ams-2.kavin.rocks',
    registration_disabled: false,
    uptime_24h: 99.754105,
    uptime_7d: 99.497665,
    uptime_30d: 47.201653
  },

  DEFAULT_REGION: 'BR',

  REGIONS: [
    'DZ',
    'AR',
    'AU',
    'AT',
    'AZ',
    'BH',
    'BD',
    'BY',
    'BE',
    'BO',
    'BA',
    'BR',
    'BG',
    'KH',
    'CA',
    'CL',
    'CO',
    'CR',
    'HR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'EC',
    'EG',
    'SV',
    'EE',
    'FI',
    'FR',
    'GE',
    'DE',
    'GH',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IN',
    'ID',
    'IQ',
    'IE',
    'IL',
    'IT',
    'JM',
    'JP',
    'JO',
    'KZ',
    'KE',
    'KW',
    'LA',
    'LV',
    'LB',
    'LY',
    'LI',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'ME',
    'MA',
    'NP',
    'NL',
    'NZ',
    'NI',
    'NG',
    'MK',
    'NO',
    'OM',
    'PK',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'PR',
    'QA',
    'RO',
    'RU',
    'SA',
    'SN',
    'RS',
    'SG',
    'SK',
    'SI',
    'ZA',
    'KR',
    'ES',
    'LK',
    'SE',
    'CH',
    'TW',
    'TZ',
    'TH',
    'TN',
    'TR',
    'UG',
    'UA',
    'AE',
    'GB',
    'US',
    'UY',
    'VE',
    'VN',
    'YE',
    'ZW'
  ],

  DEFAULT_INSTANCE_CONFIG: {
    imageProxyUrl: 'https://pipedproxy.kavin.rocks',
    countries: [
      'DZ',
      'AR',
      'AU',
      'AT',
      'AZ',
      'BH',
      'BD',
      'BY',
      'BE',
      'BO',
      'BA',
      'BR',
      'BG',
      'KH',
      'CA',
      'CL',
      'CO',
      'CR',
      'HR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'EC',
      'EG',
      'SV',
      'EE',
      'FI',
      'FR',
      'GE',
      'DE',
      'GH',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IN',
      'ID',
      'IQ',
      'IE',
      'IL',
      'IT',
      'JM',
      'JP',
      'JO',
      'KZ',
      'KE',
      'KW',
      'LA',
      'LV',
      'LB',
      'LY',
      'LI',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'ME',
      'MA',
      'NP',
      'NL',
      'NZ',
      'NI',
      'NG',
      'MK',
      'NO',
      'OM',
      'PK',
      'PA',
      'PG',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'PR',
      'QA',
      'RO',
      'RU',
      'SA',
      'SN',
      'RS',
      'SG',
      'SK',
      'SI',
      'ZA',
      'KR',
      'ES',
      'LK',
      'SE',
      'CH',
      'TW',
      'TZ',
      'TH',
      'TN',
      'TR',
      'UG',
      'UA',
      'AE',
      'GB',
      'US',
      'UY',
      'VE',
      'VN',
      'YE',
      'ZW'
    ],
    s3Enabled: true,
    registrationDisabled: false
  },

  LOCAL_STORAGE_KEYS: {
    STORAGED_INSTANCES: '@piped-saved-instances',
    CURRENT_INSTANCE: '@piped-current-instance',
    HIGHLIGTH_STREAM: '@piped-hightlight-stream'
  }
};
