import { Lang } from '@oplayer/core';

export const languages = {
  en: {
    Play: 'Play',
    Pause: 'Pause',
    Loop: 'Loop',
    Volume: 'Volume',
    'Volume: %s': 'Volume: %s',
    Mute: 'Mute',
    Speed: 'Speed',
    LIVE: 'LIVE',
    Language: 'Language',
    Screenshot: 'Screenshot',
    Subtitle: 'Subtitle',
    Quality: 'Quality',
    Fullscreen: 'Fullscreen',
    'TextDecoder Not Supported': 'TextDecoder Not Supported',
    Settings: 'Settings',
    'Picture in Picture': 'Picture in Picture',
    Danmaku: 'Danmaku',
    Display: 'Display',
    Opacity: 'Opacity',
    FontSize: 'FontSize',
    'Display Area': 'Display Area',
    Off: 'Off',
    Auto: 'Auto',
    Default: 'Default',
    Normal: 'Normal',
    '%ss': '%ss',
    Close: 'Close',
    'Can be closed after %ss': 'Can be closed after %ss'
  },
  pt: {
    Play: 'Play',
    Pause: 'Pausar',
    Loop: 'Repetir',
    Volume: 'Volume',
    'Volume: %s': 'Volume: %s',
    Mute: 'Mudo',
    Speed: 'Velocidade',
    LIVE: 'Ao vivo',
    Language: 'Idioma',
    Screenshot: 'Captura de tela',
    Subtitle: 'Legenda',
    Quality: 'Qualidade',
    Fullscreen: 'Tela cheia',
    'TextDecoder Not Supported': 'Decodificador de texto não suportado',
    Settings: 'Configurações',
    'Picture in Picture': 'Picture in Picture',
    Danmaku: 'Danmaku',
    Display: 'Exibir',
    Opacity: 'Opacidade',
    FontSize: 'Tamanho da fonte',
    'Display Area': 'Área de exibição',
    Off: 'Desligado',
    Auto: 'Automático',
    Default: 'Padrão',
    Normal: 'Normal',
    '%ss': '%ss',
    Close: 'Fechar',
    'Can be closed after %ss': 'Fechar depois de %ss'
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
} as Partial<Record<Lang, any>>;
