import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'User Page',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return <div className={'bg-blue-400 h-[100px]'}>{children}</div>;
}
